notifications:
  email: false
language: generic
addons:
  apt:
    packages:
      - m4
      - ocaml
install:
  - wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin
  - export PATH=$PATH:~/.opam/system/bin
  - opam init
  - opam update
  - opam install ocp-indent dune alcotest
script:
  - dune build
